id: I9B68FD65
ocr_import_info:
  timestamp: '2023-09-29T10:46:50.948987+00:00'
  batch_id: batch-e302
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-29 11:14:34.257291+00:00
last_modified: 2023-09-29 11:14:34.257297+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN22312
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN22312
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་གྲོས་རྒྱལ་མཚན།
  languages:
  - bo
  author: སྤྱན་སྔ་བློ་གྲོས་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9624935093848764
  ocr_word_median_confidence_index: 0.9994197
bases:
  I3CN22315:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22315
      total_pages: 638
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3CN22315.txt
    statistics:
      ocr_word_median_confidence_index: 0.99117845
      ocr_word_mean_confidence_index: 0.9393491410995768
  I3CN22314:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN22314
      total_pages: 734
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN22314.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999767
      ocr_word_mean_confidence_index: 0.9798564145708227
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
